enhancement: Website hosting (#20)
Kubaryt/GwardiaHub pull request #28
Opened 2024-04-02 13:56 UTC by Kubaryt

- Migrated database to PostgreSQL,
- Added psycopg2, dj_database_url, whitenoise, gunicorn and uvicorn packages
- Changed SECURITY_KEY into env

2024-04-02 14:40 UTC, Norbiros requested changes

2024-04-02 14:40 UTC, Norbiros commented on render.yaml
> +        value: 0
```suggestion
        value: False
```

2024-04-02 14:45 UTC, Norbiros approved these changes

2024-04-07 20:14 UTC, tapczanek1321 approved these changes

2024-04-07 20:17 UTC, merged

2024-04-09 09:39 UTC, SzczurekYT commented
@Kubaryt You changed the way you start the project (we now use docker) without changing the information in readme.
Can you update that too? (as separate prz since this one is merged already)

2024-04-09 11:49 UTC, Norbiros commented
We are not using docker. It is planned - https://github.com/Gwardia-Czapli/GwardiaHub/issues/27.

2024-04-09 13:41 UTC, SzczurekYT commented
> We are not using docker. It is planned - https://github.com/Gwardia-Czapli/GwardiaHub/issues/27.

Oops I thought render.yaml is a docker compose file.