New head block
Kubaryt/GwardiaHub pull request #39
Opened 2024-04-15 21:14 UTC by Jachu8

issue #36

2024-04-16 19:04 UTC, Kubaryt commented on core/templates/core/base.html
> +        {% block head %}
```diff
        -{% block head %}
```

2024-04-16 19:10 UTC, Kubaryt requested changes
Name branches in this schema: <resolved issue type>/<resolved issue name>, so in this case enhancement/head-block.
Name pull requests in this schema: <resolved issue type>: <what you did in this branch>, so in this case enhancement: Created `head` block
Name commits in this schema: <commit type>: <what you did in this commit>, so in this example enhancement: Created `head` block in `base.html`

2024-04-16 19:10 UTC, Kubaryt commented on core/templates/core/base.html
> +        {% endblock head %}
move {% block head %} to line 15, delete this `head` from endblock

2024-04-16 19:10 UTC, Kubaryt commented on core/templates/core/index.html
> +{% endblock head %}
```suggestion
{% endblock %}
```

2024-04-16 20:09 UTC, Kubaryt requested changes
just do https://github.com/Gwardia-Czapli/GwardiaHub/pull/39/files#r1567826489

2024-04-16 20:33 UTC, Norbiros requested changes

2024-04-16 20:33 UTC, Norbiros commented on core/templates/core/index.html
> +<script>
```suggestion
<script type="module">
```

2024-04-16 20:37 UTC, Kubaryt requested changes

2024-04-16 20:37 UTC, Kubaryt commented on core/templates/core/index.html
> +<script>
```suggestion
<script type="module">
```

2024-04-16 20:37 UTC, Kubaryt commented on core/templates/core/base.html
>      <body class="bg-main_bg text-white">
```suggestion
    <body class="bg-black text-white">
```

2024-04-17 16:42 UTC, Kubaryt approved these changes
UwU

2024-04-17 18:58 UTC, goteusz-maszyk approved these changes

2024-04-17 18:59 UTC, tapczanek1321 approved these changes

2024-04-17 19:57 UTC, Norbiros approved these changes

2024-04-17 21:26 UTC, merged