Update README.md
Kubaryt/GwardiaHub pull request #58
Opened 2024-04-23 23:39 UTC by Miszaal

check my commit guys

2024-04-24 05:17 UTC, Norbiros requested changes
Elaborate more UwU (especially for people that never played Genshin).

2024-04-24 05:17 UTC, Norbiros commented on README.md
> +  - Few ideas to enhance the game:
Remove this line

2024-04-24 05:17 UTC, Norbiros commented on README.md
> +  - wish simulator(and list of the characters you've collected already)
Missing space

2024-04-24 17:12 UTC, Miszaal commented on README.md
> +  - Few ideas to enhance the game:
why?

2024-04-24 18:10 UTC, goteusz-maszyk approved these changes

2024-04-24 18:11 UTC, Kubaryt approved these changes
apruf

2024-04-24 18:33 UTC, hexxcatee approved these changes
👍👍

2024-04-26 06:16 UTC, Norbiros requested changes
I already told @Miszaal what he needs to change.

2024-04-29 12:47 UTC, closed without merging