gh webhook signature unit test
Kubaryt/GwardiaHub pull request #82
Opened 2024-05-24 19:14 UTC by wojpo

tests for checking if signature is correct

2024-05-24 19:24 UTC, Kubaryt submitted a review, later dismissed
enchancement -> enhancement,
use kebab-case for branch names,
name PRs in such convention:
<PR_type>: PR_title
So in this case:
Feat: GH webhook signature unit test

2024-05-24 19:29 UTC, Norbiros requested changes

2024-05-24 19:29 UTC, Norbiros commented on core/tests.py
> +def generate_signature(secret, payload):
Maybe move this function to `gh_webhook_handling.py`?

2024-05-24 19:31 UTC, Sanielia commented on core/tests.py
> +def generate_signature(secret, payload):
`verify_secret` atm more or less containts this function
![image](https://github.com/Gwardia-Czapli/GwardiaHub/assets/88268063/34ab23d7-b17e-40cf-9add-2d916590601d)

2024-05-24 19:38 UTC, Norbiros commented on core/tests.py
> +def generate_signature(secret, payload):
Yes, so now we duplicate code. So to fix it he could “extract” `generate_signature` from `verify_secret` method

2024-05-24 22:43 UTC, wojpo commented on core/tests.py
> +def generate_signature(secret, payload):
I changed this looks good rn

2024-05-25 12:24 UTC, Norbiros approved these changes

2024-05-27 13:04 UTC, Kubaryt approved these changes

2024-05-27 13:05 UTC, merged